name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://root:password@localhost:5433/financeapp-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create .env.test file
        run: echo "DATABASE_URL=$DATABASE_URL" > .env.test

      - name: Generate Prisma client
        run: pnpm prisma generate

      - name: ESLint
        run: pnpm run eslint:check

      - name: Prettier
        run: pnpm run prettier:check

      - name: Test
        run: pnpm run test
